### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Add Windows support:

- Change source to GitLab repo because the current sdist doesn't include
  the cmake files required to build on windows (will be fixed in next version)
- Original cmake still need some patches to build with conda
- pytest only run on Linux. No TangoTest 3.2 available for Windows right now
  and running tests on Windows is very slow as each test has to be run separately.

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
I had to make a patch to fix compilation with python 3.10 on Windows: https://github.com/conda-forge/pytango-feedstock/pull/4/commits/0c0f00f9cc936e11c190e3e30eabdbddfb9a6a7a

Not sure it's the best way

**Comment by ajoubertza** [comment]
> I had to make a patch to fix compilation with python 3.10 on Windows: [0c0f00f](https://github.com/conda-forge/pytango-feedstock/commit/0c0f00f9cc936e11c190e3e30eabdbddfb9a6a7a)
> 
> Not sure it's the best way. An alternative seems to replace `ssize_t` with `Py_ssize_t`([jpype-project/jpype#1009](https://github.com/jpype-project/jpype/issues/1009)).

I think replacing the definitions is better.  There are many places we can change, but doing it for `pipe.cpp` is probably sufficient for this patch.  See https://gitlab.com/tango-controls/pytango/-/merge_requests/449

**Comment by beenje** [comment]
> I think replacing the definitions is better. There are many places we can change, but doing it for `pipe.cpp` is probably sufficient for this patch. See https://gitlab.com/tango-controls/pytango/-/merge_requests/449

Thanks! I applied your patch to `pipe.cpp` and `device_proxy.cpp`.

**Pull request merged**
