### PR TITLE
Add aarch64 support

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by ajoubertza** [comment]
@beenje Are you aware of these apparent omniorb bugs for aarch64? https://gitlab.com/tango-controls/pytango/-/issues/449#note_1424061369
Do we need to fix omniorb first, before making PyTango builds?

**Comment by beenje** [comment]
> @beenje Are you aware of these apparent omniorb bugs for aarch64? https://gitlab.com/tango-controls/pytango/-/issues/449#note_1424061369
> Do we need to fix omniorb first, before making PyTango builds?

Good point. Sounds like we should. I guess I'll have to recompile cpptango as well.
I guess the tests should fail then. Will wait and see. Maybe I should try travis... Had issue in the past but they had some HW. On azure, it's emulated and very slow.

**Comment by beenje** [comment]
I applied some patches from svn to omniorb: https://github.com/conda-forge/omniorb-feedstock/pull/39 and rebuilt as well cpptango 9.4.1 after that.

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
Tests on ppc64le keep failing (same issue we have sometimes in CI). We could maybe skip the tests for this arch... Not great...
Or only add aarch64. Not sure many people are interested in ppc64le. Maybe no need to add it for now.

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
